a

diff --git a/.github/workflows/workflow-delete.yml b/.github/workflows/workflow-delete.yml
--- a/.github/workflows/workflow-delete.yml
+++ b/.github/workflows/workflow-delete.yml
@@ -16,43 +16,56 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-     
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Check existence of config.yaml 
+        id: check_file
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "config.yaml"
+      - name: Files don't exist
+        if: steps.check_file.outputs.files_exists == 'false'
+        run: |
+          echo "failed"
+          exit 1
+      
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with: 
+          python-version: "3.x"
+      
+      - run: pip install PyYAML
+        name: Install py dependencies
+
+      - name: Create outputs from config file
+        run: |
+          echo "##[set-output name=app-name;]$(python create-outputs-from-config.py app-name)"
+          echo "##[set-output name=argocd-repo;]$(python create-outputs-from-config.py argocd-repo)"
+        id: from-config
+        
       - name: set environment variables
         uses: allenevans/set-env@v2.0.0
         with:
           CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
           TIER: ${{ github.event.inputs.tier}}
-          APP_NAME: ${{secrets.APP_NAME}}
-
-      - name: Check out code
-        uses: actions/checkout@v2
     
-      - name: Setup Python
-        uses: actions/setup-python@v2
-        with: 
-          python-version: "3.x"
-     
       - run: python delete-overlays-dir.py
-        name: Delete dir from kustomize overlays
-    
+        name: Delete dir from kustomize overlays 
 
       - name: Add and commit changes
         uses: EndBug/add-and-commit@v6
         with:
           message: "deleted kustomize dir"
   
-  trigger-workflow:
-    name: Trigger workflow in ArgoCD repo
-    runs-on: ubuntu-latest
-    needs: delete
-    steps:
-      
+ 
       - name: Trigger infrastructure repo workflow
         uses: benc-uk/workflow-dispatch@v1
         with:
           workflow: delete-manifest
           ref: master
-          inputs: '{"code-branch" : "${{ github.event.inputs.code-branch}}", "tier" : "${{ github.event.inputs.tier}}", "app-name" : "${{secrets.APP_NAME}}"}'
-          repo: ${{ github.repository_owner }}/${{ secrets.ARGOCD_REPO }}
+          inputs: '{"code-branch" : "${{ github.event.inputs.code-branch}}", "tier" : "${{ github.event.inputs.tier}}", "app-name" : "${{steps.from-config.outputs.app-name}}"}'
+          repo: ${{ github.repository_owner }}/${{ steps.from-config.outputs.argocd-repo }}
           token: ${{ secrets.PAT_TOKEN }}
            
diff --git a/.github/workflows/workflow-update.yml b/.github/workflows/workflow-update.yml
--- a/.github/workflows/workflow-update.yml
+++ b/.github/workflows/workflow-update.yml
@@ -2,8 +2,8 @@ name: update-infrastructure
 on: 
   workflow_dispatch:
     inputs:
-      docker-image-tag:
-        description: 'this is the docker tag build in the code workflow'     
+      docker-image:
+        description: 'This is the docker built in the code workflow'     
         required: true
       code-branch:
         description: 'branch of code repo'
@@ -20,47 +20,98 @@ on:
       docker-backend-repo:
         description: 'the repo name on dockerhub for the backend image'
         required: true
+      default-input-flag:
+        description: 'it specifies where to fetch input.yaml file'
+        required: true
+      backup-input-repo:
+        description: 'the repo where backup input.files are stored'
+        required: true
       
-
 jobs:
-  update-values:
+  update-kustomize:
     name: Update kustomize
     runs-on: ubuntu-latest
     
     steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Check existence of config.yaml 
+        id: check_file
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "config.yaml"
+      - name: Files don't exist
+        if: steps.check_file.outputs.files_exists == 'false'
+        run: |
+          echo "failed"
+          exit 1
       
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with: 
+          python-version: "3.x"
+      
+      - run: pip install PyYAML
+        name: Install py dependencies
+
+      - name: Create outputs from config file
+        run: |
+          echo "##[set-output name=app-name;]$(python create-outputs-from-config.py app-name)"
+          echo "##[set-output name=argocd-repo;]$(python create-outputs-from-config.py argocd-repo)"
+          echo "##[set-output name=prod_input_master;]$(python create-outputs-from-config.py prod-input-master)"
+        id: from-config
+        
       - name: set environment variables
         uses: allenevans/set-env@v2.0.0
         with:
-          DOCKER_TAG: ${{ github.event.inputs.docker-image-tag}}
+          DOCKER_IMAGE: ${{ github.event.inputs.docker-tag}}
           CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
           CODE_REPO: ${{ github.event.inputs.code-repo}}
           TIER: ${{ github.event.inputs.tier}}
           DOCKER_BACKEND_REPO: ${{ github.event.inputs.docker-backend-repo}}
           DOCKER_FRONTEND_REPO: ${{ github.event.inputs.docker-frontend-repo}}
           DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
-          APP_NAME: ${{secrets.APP_NAME}}
-
-      - name: Check out code
-        uses: actions/checkout@v2
+          APP_NAME: ${{steps.from-config.outputs.app-name}}
+          PROD_INPUT_MASTER: ${{steps.from-config.outputs.app-name}}
       
       - name: Checkout code repo
+        if: github.event.inputs.default-input-flag == 'false'
         uses: actions/checkout@v2
         with:
             repository: ${{ github.repository_owner }}/${{ github.event.inputs.code-repo}}
             token: ${{secrets.PAT_TOKEN}}
             ref: ${{ github.event.inputs.code-branch}}
-            path: code-repo
-      - run: cp code-repo/input.yaml ./input.yaml
+            path: other-repo
       
-      - name: Setup Python
-        uses: actions/setup-python@v2
-        with: 
-          python-version: "3.x"
+      - name: Checkout backup input repo
+        if: github.event.inputs.default-input-flag == 'true'
+        uses: actions/checkout@v2
+        with:
+            repository: ${{ github.repository_owner }}/${{ github.event.inputs.backup-input-repo }}
+            token: ${{secrets.PAT_TOKEN}}
+            ref: master
+            path: other-repo
 
-      - run: pip install PyYAML
-        name: Install py dependencies
-        
+      - if: github.event.inputs.default-input-flag == 'false'
+        run: cp other-repo/input.yaml ./input.yaml
+      
+      - if: github.event.inputs.default-input-flag == 'true'
+        run: |
+          var=${{github.event.inputs.code-branch}}
+          if grep -q "master" <<< "$var"; then
+          cp other-repo/default-input-files/prod/input.yaml ./input.yaml
+          elif grep -q "features" <<< "$var"; then
+          cp other-repo/default-input-files/feature/input.yaml ./input.yaml
+          elif grep -q "releases" <<< "$var"; then
+          cp other-repo/default-input-files/release/input.yaml ./input.yaml
+          fi
+      
+      - name: Set the correct branch name in input.yaml
+        if: github.event.inputs.default-input-flag == 'true'
+        run: python update-branch-name.py
+
       - name: Create kustomize overlays dir, if necessary
         run: python overlays-dir-creation.py
         
@@ -72,25 +123,20 @@ jobs:
       
       - run: rm -f input.yaml
         
-      - run: rm -rf code-repo/
+      - run: rm -rf other-repo/
 
       - name: Add and commit changes
         uses: EndBug/add-and-commit@v6
         with:
           message: 'updated kustomize files'
   
-  trigger-workflow:
-    name: Trigger workflow in ArgoCD repo
-    runs-on: ubuntu-latest
-    needs: update-values
-    steps:
       
       - name: Trigger infrastructure repo workflow
         uses: benc-uk/workflow-dispatch@v1
         with:
           workflow: update-manifest
           ref: master
-          inputs: '{"code-branch" : "${{ github.event.inputs.code-branch}}", "tier" : "${{ github.event.inputs.tier}}", "code-repo" : "${{github.event.inputs.code-repo}}", "app-name" : "${{secrets.APP_NAME}}"}'
-          repo: ${{ github.repository_owner }}/${{ secrets.ARGOCD_REPO }}
+          inputs: '{"code-branch" : "${{ github.event.inputs.code-branch}}", "tier" : "${{ github.event.inputs.tier}}", "code-repo" : "${{github.event.inputs.code-repo}}", "app-name" : "${{steps.from-config.outputs.app-name}}", "default-input-flag" : "${{github.event.inputs.default-input-flag}}", "backup-input-repo" : "${{github.event.inputs.backup-input-repo}}" }'
+          repo: ${{ github.repository_owner }}/${{ steps.from-config.outputs.argocd-repo}}
           token: ${{ secrets.PAT_TOKEN }}
 
